### PR TITLE
fixing batch and experiment download

### PR DESCRIPTION
**Pull request by campbellla**
Fixed bugs with experiment downloads/annotation and protein batch_search functions

### CODE REVIEW

**Comment by knaegle** [comment]
### Batch Search
**Issue 1**:  if you attempt to run batch search without logging in, you get an error. So we should either report a specific error (like: "To use this feature please log in") or, selecting it if you aren't logged in should take you to the login page, or we add an email like is there for Download Experiment (though, see below). Error if you add proteins then run batch search is here. 
Screenshot 2024-06-04 at 8 47 00 AM


**Issue 2**: I logged in after password reset (which worked!) and all I see is that my attempt at a batch search has an error. 
Screenshot 2024-06-04 at 8 51 44 AM

### Experiment Download
The first attempt I made gave an error
Screenshot 2024-06-04 at 8 46 32 AM

The second attempt I made, I was logged into the system, I selected a different experiment and I did not select annotate.
The third attempt I made, I was logged in, I selected a third experiment, no annotate
Fourth attempt, logged in, back to first experiment, added annotate. 

Hence, it seems that although we allow people to give their email, the system still requires that the user have a log in and be actively logged in. If we require log in, then we don't need the email form, since we can use the user login as we might for a batch search. 

If we use login, which I know think we should just require for both the download and the batch search, then in addition to an email response, it would be helpful to link the results on the person's job page (image here of the job page), when it says finished, could it possibly say finished and a link to the site? Or link on the first column? 
Screenshot 2024-06-04 at 9 00 08 AM

**Comment by campbellla** [comment]
Improved UI to include login button on batch page if not logged in and automated redirects to login with flash messaging for attempts at task submission.

**Comment by campbellla** [comment]
On most recent pushes, have made the batch and experiment download easily accessible from my experiments page that contain a hyperlink result url. Once clicked, it automatically downloads the associated file. Also, made each of these features only accessible for registered users with re-directs for unregistered or not signed in users.

**Comment by knaegle** [comment]
Testing now. 

Batch search has a nice page that is clear about the job being submitted, and what happens next (Screenshot attached). Download experiments stays on the same page with the open button and just adds a line, so it would be great if we did the same kind of thing on Download Experiments. 

Screenshot 2024-06-21 at 6 37 10 PM


Also, let's make annotation the default behavior for download. I think we can even remove it. Or we could have two buttons: 
Download Original Data
Download with Annotation

**Review by knaegle — APPROVED** [review]
Merging the pull request - most functions, except for some strange issue on download return for my account.

**Pull request merged**
